# Generated by Django 5.1.2 on 2024-10-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_department_alter_student_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
    ]
