# Generated by Django 5.1.2 on 2024-10-15 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_course_unit_student_result_remark_student_tgp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursescores',
            options={'verbose_name': 'Course Score', 'verbose_name_plural': 'Course Scores'},
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.department'),
        ),
    ]
