# Generated by Django 5.1.2 on 2024-10-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_coursescores_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AlterField(
            model_name='student',
            name='hall_of_residence',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PTDF', 'PTDF'), ('NOBLE', 'Noble'), ('OLD', 'Old')], max_length=100, null=True),
        ),
    ]
